from typing import Dict, Any
from backend.services.orchestration.agents.registry import AgentBase, AgentMetadata
from backend.services.orchestration.prompts.registry import PromptRegistry
from backend.services.orchestration.providers.mock_provider import MockProvider
import json

class MemoryAgent(AgentBase):
    def __init__(self):
        super().__init__()
        self.metadata = AgentMetadata(
            name="MemoryAgent",
            description="Recalls past interactions and vector memory.",
            version="1.0.0",
            enabled=True,
            priority=2,
            allowed_tools=["retrieve_semantic_memory", "store_semantic_memory"],
            allowed_collections=["past_doubts", "session_logs", "learning_dna"],
            max_tokens=4096,
            temperature=0.3,
            timeout_ms=3000,
            retry_count=2
        )
        self.capabilities = ["memory_retrieval", "memory_storage"]
        self.execution_policy = "synchronous"
        self.retry_policy = "exponential_backoff"
        self.max_iterations = 2

    def health_check(self) -> bool:
        return True

    def can_handle(self, query: str) -> bool:
        return "remember" in query.lower() or "last time" in query.lower()

    def validate_input(self, unified_context: Dict[str, Any], query: str) -> bool:
        if "user" not in unified_context.get("static_context", {}):
            return False
        return True

    def validate_output(self, response: Dict[str, Any]) -> bool:
        return "memory_context" in response

    def execute(self, unified_context: Dict[str, Any], query: str) -> Dict[str, Any]:
        if not self.validate_input(unified_context, query):
            raise ValueError("Invalid input for MemoryAgent")
            
        prompt = PromptRegistry().get_prompt(self.metadata.name)
        provider = MockProvider()
        
        provider_result = provider.generate(
            prompt=prompt,
            context=unified_context,
            query=query,
            allowed_tools=self.metadata.allowed_tools
        )
        
        try:
            parsed = json.loads(provider_result["response"])
        except:
            parsed = {"memory_context": provider_result["response"]}
            
        response = {
            "memory_context": parsed.get("memory_context", ""),
            "tools_used": provider_result["tools_used"] + parsed.get("tools_used", []),
            "telemetry": provider_result["telemetry"]
        }
        
        if not self.validate_output(response):
            raise ValueError("Invalid output generated by MemoryAgent")
            
        return response
