from typing import Dict, Any
from backend.services.orchestration.agents.registry import AgentBase, AgentMetadata
from backend.services.orchestration.prompts.registry import PromptRegistry
from backend.services.orchestration.providers.mock_provider import MockProvider
import json

class TutorAgent(AgentBase):
    def __init__(self):
        super().__init__()
        self.metadata = AgentMetadata(
            name="TutorAgent",
            description="Direct pedagogical interaction and explanations.",
            version="1.0.0",
            enabled=True,
            priority=1,
            allowed_tools=["selectExplanationLevel"],
            allowed_collections=[],
            max_tokens=4096,
            temperature=0.6,
            timeout_ms=8000,
            retry_count=1
        )
        self.capabilities = ["explanation", "scaffolding"]
        self.execution_policy = "synchronous"
        self.retry_policy = "exponential_backoff"
        self.max_iterations = 1

    def health_check(self) -> bool:
        return True

    def can_handle(self, query: str) -> bool:
        return True

    def validate_input(self, unified_context: Dict[str, Any], query: str) -> bool:
        if not query:
            return False
        return True

    def validate_output(self, response: Dict[str, Any]) -> bool:
        if "text" not in response:
            return False
        return True

    def execute(self, unified_context: Dict[str, Any], query: str) -> Dict[str, Any]:
        if not self.validate_input(unified_context, query):
            raise ValueError("Invalid input for TutorAgent")
            
        prompt = PromptRegistry().get_prompt(self.metadata.name)
        provider = MockProvider()
        
        provider_result = provider.generate(
            prompt=prompt,
            context=unified_context,
            query=query,
            allowed_tools=self.metadata.allowed_tools
        )
        
        response = {
            "text": provider_result["response"],
            "tools_used": provider_result["tools_used"],
            "telemetry": provider_result["telemetry"]
        }
        
        if not self.validate_output(response):
            raise ValueError("Invalid output generated by TutorAgent")
            
        return response
