import React, { useState } from "react";
import { TrendingUp, Calendar, Sparkles, CheckCircle2, Clock, Plus } from "lucide-react";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";
import { AIResponseCard } from "@/components/widgets/AIResponseCard";
import { RecommendationCard } from "@/components/widgets/RecommendationCard";

export const StudyPlannerPage: React.FC = () => {
  const [generating, setGenerating] = useState(false);

  const schedule = [
    { day: "Today (Monday)", tasks: [{ title: "Complete Module 3 Video Lecture", time: "10:00 AM - 11:30 AM", course: "Agentic Coding", status: "done" }, { title: "Run Qdrant Vector Memory Sandbox", time: "2:00 PM - 3:00 PM", course: "Vector Systems", status: "pending" }] },
    { day: "Tomorrow (Tuesday)", tasks: [{ title: "Review Enkrypt Safety Interceptors", time: "9:30 AM - 11:00 AM", course: "Security", status: "pending" }, { title: "Mock Technical Interview Practice", time: "4:00 PM - 5:00 PM", course: "Career Prep", status: "pending" }] },
    { day: "Wednesday", tasks: [{ title: "Kubernetes Cluster Autoscaling Lab", time: "1:00 PM - 4:00 PM", course: "Cloud Architecture", status: "pending" }] },
  ];

  const handleGenerate = () => {
    setGenerating(true);
    setTimeout(() => setGenerating(false), 1000);
  };

  return (
    <div className="space-y-8 py-6">
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-4 border-b border-obsidian-600 pb-6">
        <div>
          <Badge variant="purple">AI Study Orchestrator</Badge>
          <h1 className="text-3xl font-extrabold text-white mt-1">Adaptive Study Planner</h1>
          <p className="text-sm text-slate-400 mt-1">Dynamic schedules generated by your Digital Twin based on retention curves and target exam dates.</p>
        </div>
        <Button size="md" onClick={handleGenerate} isLoading={generating} leftIcon={<Sparkles className="w-4 h-4 text-indigo-400" />}>
          Re-Optimize Schedule with AI
        </Button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-6">
          <AIResponseCard
            title="Mastra Scheduler Swarm"
            content="I optimized your weekly schedule by moving the Kubernetes lab to Wednesday afternoon, when your cognitive retention velocity for systems architecture is historically 22% higher."
            confidenceScore={0.98}
          />

          <div className="space-y-6">
            {schedule.map((group, idx) => (
              <Card key={idx} variant="default" className="p-5 space-y-4">
                <div className="flex items-center justify-between pb-3 border-b border-obsidian-600">
                  <h3 className="font-bold text-base text-white flex items-center gap-2">
                    <Calendar className="w-4 h-4 text-primary-500" /> {group.day}
                  </h3>
                  <Badge variant="default">{group.tasks.length} Sessions</Badge>
                </div>
                <div className="space-y-3">
                  {group.tasks.map((task, tIdx) => (
                    <div key={tIdx} className="p-3.5 rounded-xl bg-obsidian-900/80 border border-obsidian-600 flex items-center justify-between hover:border-indigo-500/30 transition-all">
                      <div className="flex items-start space-x-3">
                        <button className="mt-0.5 text-slate-400 hover:text-emerald-400 transition-colors">
                          <CheckCircle2 className={`w-5 h-5 ${task.status === "done" ? "text-emerald-400 fill-emerald-400/20" : ""}`} />
                        </button>
                        <div>
                          <h4 className={`text-sm font-semibold ${task.status === "done" ? "line-through text-slate-500" : "text-white"}`}>{task.title}</h4>
                          <div className="flex items-center space-x-3 mt-1 text-xs text-slate-400">
                            <span className="flex items-center gap-1"><Clock className="w-3 h-3" /> {task.time}</span>
                            <Badge variant="purple" size="sm">{task.course}</Badge>
                          </div>
                        </div>
                      </div>
                      <Badge variant={task.status === "done" ? "success" : "primary"}>
                        {task.status === "done" ? "Completed" : "Scheduled"}
                      </Badge>
                    </div>
                  ))}
                </div>
              </Card>
            ))}
          </div>
        </div>

        <div className="space-y-6">
          <RecommendationCard
            title="Focus Block: 45 Min Pomodoro"
            description="Your Digital Twin recommends a 45-minute uninterrupted study block for Qdrant vector indexing before your afternoon lab."
            category="Optimal Timing"
            priority="high"
          />
        </div>
      </div>
    </div>
  );
};
